import LegalPageLayout, { LegalSection } from '@/components/LegalPageLayout';

const SECTIONS: LegalSection[] = [
  {
    id: 'preamble',
    title: 'Preamble',
    body: (
      <p>
        This Privacy Policy (&quot;Policy&quot;) is published in accordance with the provisions of Rule 3(1) of
        the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and
        the Digital Personal Data Protection Act, 2023, read with the Information Technology Act, 2000. This
        Policy is an &apos;electronic record&apos; as contemplated under Section 2(t) of the Information
        Technology Act, 2000, and is generated by a computer system — it does not require any physical or
        digital signature.
      </p>
    ),
  },
  {
    id: 'introduction',
    title: 'Introduction',
    body: (
      <>
        <p>
          The online store arviik.in (&quot;Online Store&quot;, &quot;Site&quot;) is owned and operated by{' '}
          <strong>ARVIIK</strong> (&quot;ARVIIK&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), under the laws of India, with
          its registered office in Ahmedabad, Gujarat, India.
        </p>
        <p>
          Users are requested to read and understand this Policy carefully before using or accessing the
          Online Store. Through this Policy, ARVIIK intends to convey the manner in which your information is
          collected and used while you access our Site and services. This Policy is binding on every user of
          the Online Store — if you do not agree with the terms of this Policy, please do not use or access
          the Site.
        </p>
        <p>
          ARVIIK reserves the right to change, edit, alter, amend, revise, or substitute this Policy at any
          time, with or without prior notice. By continuing to use the Online Store after such a change, you
          signify that you have read, understood, and agree to be bound by the updated Policy.
        </p>
      </>
    ),
  },
  {
    id: 'collect',
    title: 'Information We Collect',
    body: (
      <>
        <p><strong>Information you give us directly</strong> when you create an account, checkout, or contact us:</p>
        <ul>
          <li>Name, email address, and phone number</li>
          <li>Shipping address, city, state, and pincode</li>
          <li>Order history and items in your cart or wishlist</li>
          <li>Messages you send through the Contact page or support email/WhatsApp</li>
        </ul>
        <p className="pt-1"><strong>Information collected automatically</strong> as you browse:</p>
        <ul>
          <li>Device and browser type, IP address, and approximate location</li>
          <li>Pages viewed, products browsed, and time spent on the Site</li>
          <li>Cookies and local storage used to keep you signed in, remember your cart, and measure site performance</li>
        </ul>
        <p className="pt-1">
          <strong>Payment information</strong> is collected and processed directly by Razorpay, our payment
          gateway — we never see or store your full card number, CVV, or UPI PIN. See our{' '}
          <a href="/payment-policy">Payment Policy</a>{' '}for details.
        </p>
      </>
    ),
  },
  {
    id: 'use',
    title: 'How We Use Your Information',
    body: (
      <ul>
        <li>To process, pack, ship, and deliver your orders, and to keep you updated on their status</li>
        <li>To verify deliverability of your address before an order is placed</li>
        <li>To respond to support requests and resolve issues with an order</li>
        <li>To send order confirmations, shipping updates, and (only if you&apos;ve opted in) marketing communications about new drops and offers</li>
        <li>To detect and prevent fraud, abuse, or security incidents</li>
        <li>To comply with applicable law, including tax and accounting obligations</li>
        <li>To improve the Site — what people browse, where they drop off, what doesn&apos;t work</li>
      </ul>
    ),
  },
  {
    id: 'sharing',
    title: 'Disclosure of Information',
    body: (
      <>
        <p>
          We do not sell, trade, or rent your personal data to third parties. We disclose it only to the
          following categories of recipients, each bound to use it only for the stated purpose:
        </p>
        <ul>
          <li><strong>Razorpay</strong> — to process payments securely.</li>
          <li><strong>NimbusPost</strong> and our courier partners — to check deliverability and ship your order.</li>
          <li><strong>Supabase</strong> — our database and authentication provider, which stores your account and order data.</li>
          <li>Government authorities, law enforcement, or regulators, where required by applicable law, court order, or governmental request.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'cookies',
    title: 'Cookies & Local Storage',
    body: (
      <p>
        We use cookies and browser local storage to keep you signed in, remember what&apos;s in your cart and
        wishlist between visits, and understand how the Site is used so we can improve it. You may configure
        your browser to refuse or delete cookies, though certain features of the Site (such as a persistent
        cart) may not function properly as a result.
      </p>
    ),
  },
  {
    id: 'security',
    title: 'Data Security',
    body: (
      <p>
        We implement reasonable security practices and procedures, including encryption of data at rest and
        in transit, in accordance with Section 43A of the Information Technology Act, 2000 and the applicable
        rules made thereunder. Access to your personal data is restricted to systems and personnel that need
        it to operate the Site. No method of transmission or electronic storage is 100% secure, and we cannot
        guarantee absolute security.
      </p>
    ),
  },
  {
    id: 'retention',
    title: 'Data Retention',
    body: (
      <p>
        We retain your personal data for as long as your account remains active, and thereafter for such
        period as is necessary to comply with our legal, tax, and accounting obligations, resolve disputes,
        and enforce our agreements. Where you request deletion of your account, we will delete or anonymise
        personal data that we are not legally required to retain.
      </p>
    ),
  },
  {
    id: 'rights',
    title: 'Your Rights',
    body: (
      <>
        <p>Subject to applicable law, you have the right to:</p>
        <ul>
          <li>Access or correct your personal data from your Profile page at any time.</li>
          <li>Request a copy of the personal data we hold about you.</li>
          <li>Withdraw consent and request erasure of your personal data, subject to what we are legally required to retain.</li>
          <li>Unsubscribe from marketing communications at any time using the link provided in any such communication.</li>
        </ul>
        <p className="pt-1">
          To exercise any of these rights, write to us at{' '}
          <a href="mailto:info@arviik.in">info@arviik.in</a>{' '}from the email address associated with
          your account.
        </p>
      </>
    ),
  },
  {
    id: 'grievance',
    title: 'Grievance Officer',
    body: (
      <>
        <p>
          In accordance with the Information Technology Act, 2000 and the rules made thereunder, and the
          Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer
          are provided below. If you have any grievance with respect to this Policy or the processing of your
          personal data, please contact:
        </p>
        <ul>
          <li><strong>Name:</strong> Grievance Officer, ARVIIK</li>
          <li><strong>Email:</strong> <a href="mailto:info@arviik.in">info@arviik.in</a></li>
          <li><strong>Address:</strong> ARVIIK HQ, Ahmedabad, Gujarat, India</li>
          <li><strong>Response Time:</strong> We will acknowledge your complaint within 48 hours and endeavour to redress it within one month of receipt.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'children',
    title: "Children's Privacy",
    body: (
      <p>
        ARVIIK is not directed at individuals under 18 years of age, and we do not knowingly collect personal
        information from anyone under that age. If you believe a minor has provided us with personal data,
        contact us and we will take steps to remove it.
      </p>
    ),
  },
  {
    id: 'changes',
    title: 'Changes to This Policy',
    body: (
      <p>
        We may update this Privacy Policy from time to time to reflect changes in our practices or as
        required by law. The &quot;Last updated&quot; date at the top of this page always reflects the current
        version.
      </p>
    ),
  },
  {
    id: 'contact',
    title: 'Contact Us',
    body: (
      <p>
        For any queries regarding this Policy, write to us at{' '}
        <a href="mailto:info@arviik.in">info@arviik.in</a> or through our{' '}
        <a href="/contact">Contact page</a>.
      </p>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      eyebrow="Your Data, Handled Right"
      title="Privacy Policy"
      intro="What we collect, why we collect it, and the choices you have — with the legal grounding Indian law requires."
      lastUpdated="September 5, 2026"
      sections={SECTIONS}
    />
  );
}
